<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="210373" started-at="2015-07-17T21:56:03Z" finished-at="2015-07-17T21:59:33Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="210373" started-at="2015-07-17T21:56:03Z" finished-at="2015-07-17T21:59:33Z">
      <class name="com.ecofactor.realtemp.RealTemp">
        <test-method status="PASS" signature="init()[pri:0, instance:com.ecofactor.realtemp.RealTemp@56d15836]" name="init" is-config="true" duration-ms="121" started-at="2015-07-17T14:56:03Z" finished-at="2015-07-17T14:56:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="createRealTempForCoolThermostat_cool_130()[pri:0, instance:com.ecofactor.realtemp.RealTemp@56d15836]" name="createRealTempForCoolThermostat_cool_130" duration-ms="210222" started-at="2015-07-17T14:56:03Z" finished-at="2015-07-17T14:59:33Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [32753] but found [0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [32753] but found [0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at org.testng.Assert.assertEquals(Assert.java:380)
	at com.ecofactor.realtemp.RealTemp.createRealTempForCoolThermostat_cool_130(RealTemp.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createRealTempForCoolThermostat_cool_130 -->
      </class> <!-- com.ecofactor.realtemp.RealTemp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
