<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="642246" started-at="2015-05-19T23:05:26Z" finished-at="2015-05-19T23:16:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="642246" started-at="2015-05-19T23:05:26Z" finished-at="2015-05-19T23:16:09Z">
      <class name="com.ecofactor.spo.SPO">
        <test-method status="PASS" signature="init()[pri:0, instance:com.ecofactor.spo.SPO@1b74318a]" name="init" is-config="true" duration-ms="110" started-at="2015-05-19T16:05:26Z" finished-at="2015-05-19T16:05:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="createSpoAwayBeforeSPOstartFoSPODuration()[pri:0, instance:com.ecofactor.spo.SPO@1b74318a]" name="createSpoAwayBeforeSPOstartFoSPODuration" duration-ms="642126" started-at="2015-05-19T16:05:26Z" finished-at="2015-05-19T16:16:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Expected set_point_reason AWAY expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Expected set_point_reason AWAY expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at com.ecofactor.spo.SPO.createSpoAwayBeforeSPOstartFoSPODuration(SPO.java:665)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSpoAwayBeforeSPOstartFoSPODuration -->
      </class> <!-- com.ecofactor.spo.SPO -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
